default: &default
  adapter: mysql2
  encoding: utf8
  pool: 10
  username: <%= ENV['DB_USERNAME'] || 'root' %>
  password:
  reconnect: true
  host: <%= ENV['DB_HOST'] || '127.0.0.1' %>

development:
  <<: *default
  database: "demanda_development"

test:
  <<: *default
  database: "demanda_test"

production:
  <<: *default
  database: "demanda"
